version: "3.9"

services:
  api:
    container_name: api_capstone
    build: .
    ports:
      - 3000:3000
    environment:
      - DB_HOST=db
      - DB_PASSWORD=1234
      - DB=capstone_m4
      - DB_USER=os_guri
      - SECRET_KEY=sua_chave_secreta
    depends_on:
      db:
        condition: service_healthy
    volumes:
      - .:/app

  db:
    container_name: capstone
    image: postgres:14
    ports:
      - 5430:5432
    environment:
      - POSTGRES_USER=os_guri
      - POSTGRES_PASSWORD=1234
      - POSTGRES_DB=capstone_m4
    healthcheck:
      test: ["CMD-SHELL", "pg_isready -U os_guri -d capstone_m4"]
      interval: 10s
      timeout: 5s
      retries: 5
      start_period: 5s
